<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <RootNamespace>Cyber_Espace_Entrainement</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Helpers\" />
    <Folder Include="Models\AnalyseLogs\" />
    <Folder Include="Models\BrokenAccess\" />
    <Folder Include="Models\BruteForce\" />
    <Folder Include="Models\Captcha\" />
    <Folder Include="Models\Chiffrement\" />
    <Folder Include="Models\Clickjacking\" />
    <Folder Include="Models\ConventionNommage\" />
    <Folder Include="Models\ElevationPrivilege\" />
    <Folder Include="Models\InjectionIA\" />
    <Folder Include="Models\InjectionSQL\" />
    <Folder Include="Models\Phishing\" />
    <Folder Include="Models\Ransomware\" />
    <Folder Include="Models\Steganographie\" />
    <Folder Include="Models\Token\" />
    <Folder Include="Models\UserEnumeration\" />
    <Folder Include="Models\XSS\" />
    <Folder Include="Resources\Clickjacking\" />
    <Folder Include="Resources\InjectionSQL\" />
    <Folder Include="Resources\InjectionIA\" />
    <Folder Include="Resources\BrokenAccess\" />
    <Folder Include="Resources\Captcha\" />
    <Folder Include="Resources\Chiffrement\" />
    <Folder Include="Resources\ConventionNommage\" />
    <Folder Include="Resources\AnalyseLogs\" />
    <Folder Include="Resources\ElevationPrivilege\" />
    <Folder Include="Resources\BruteForce\" />
    <Folder Include="Resources\UserEnumeration\" />
    <Folder Include="Resources\XSS\" />
    <Folder Include="Resources\Token\" />
    <Folder Include="Resources\Ransomware\" />
    <Folder Include="Resources\Phishing\" />
    <Folder Include="Resources\Steganographie\" />
    <Folder Include="ViewModels\Tests\AnalyseLogs\" />
    <Folder Include="ViewModels\Tests\BrokenAccess\" />
    <Folder Include="ViewModels\Tests\BruteForce\" />
    <Folder Include="ViewModels\Tests\Captcha\" />
    <Folder Include="ViewModels\Tests\Chiffrement\" />
    <Folder Include="ViewModels\Tests\Clickjacking\" />
    <Folder Include="ViewModels\Tests\ConventionNommage\" />
    <Folder Include="ViewModels\Tests\ElevationPrivilege\" />
    <Folder Include="ViewModels\Tests\InjectionIA\" />
    <Folder Include="ViewModels\Tests\InjectionSQL\" />
    <Folder Include="ViewModels\Tests\Phishing\" />
    <Folder Include="ViewModels\Tests\Ransomware\" />
    <Folder Include="ViewModels\Tests\Steganographie\" />
    <Folder Include="ViewModels\Tests\Token\" />
    <Folder Include="ViewModels\Tests\UserEnumeration\" />
    <Folder Include="ViewModels\Tests\XSS\" />
    <Folder Include="Views\Tests\AnalyseLogs\" />
    <Folder Include="Views\Tests\BrokenAccess\" />
    <Folder Include="Views\Tests\BruteForce\" />
    <Folder Include="Views\Tests\Captcha\" />
    <Folder Include="Views\Tests\Chiffrement\" />
    <Folder Include="Views\Tests\Clickjacking\" />
    <Folder Include="Views\Tests\ConventionNommage\" />
    <Folder Include="Views\Tests\ElevationPrivilege\" />
    <Folder Include="Views\Tests\InjectionIA\" />
    <Folder Include="Views\Tests\InjectionSQL\" />
    <Folder Include="Views\Tests\Phishing\" />
    <Folder Include="Views\Tests\Ransomware\" />
    <Folder Include="Views\Tests\Steganographie\" />
    <Folder Include="Views\Tests\Token\" />
    <Folder Include="Views\Tests\UserEnumeration\" />
    <Folder Include="Views\Tests\XSS\" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
